site_name: Open Court Data India
site_description: Documentation for the Open Court Data India project
site_author: Varun Hemachandran
site_url: https://varun-heman.github.io/open-court-data-india/
repo_url: https://github.com/varun-heman/open-court-data-india
repo_name: varun-heman/open-court-data-india

# GitHub Pages deployment configuration
use_directory_urls: false

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - attr_list

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          options:
            show_source: true
            show_root_heading: true
            heading_level: 3

copyright: Copyright &copy; 2025 <a href="https://github.com/varun-heman">Varun Hemachandran</a>

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/varun-heman
  generator: false

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
    - Quick Start: getting-started/quick-start.md
  - User Guide:
    - Overview: user-guide/overview.md
    - Scrapers: user-guide/scrapers.md
    - Database Integration: user-guide/database-integration.md
    - API: user-guide/api.md
    - Tagging System: user-guide/tagging-system.md
  - API Reference:
    - Scrapers: api-reference/scrapers.md
    - Database: api-reference/database.md
    - Utilities: api-reference/utilities.md
  - Developer Guide:
    - Architecture: developer-guide/architecture.md
    - Contributing: developer-guide/contributing.md
    - Code Style: developer-guide/code-style.md
    - Code of Conduct: developer-guide/code-of-conduct.md
  - About:
    - Changelog: about/changelog.md
    - License: about/license.md
