site_name: Open Court Data India
site_url: https://varun-heman.github.io/open-court-data-india/
repo_url: https://github.com/varun-heman/open-court-data-india
repo_name: varun-heman/open-court-data-india

use_directory_urls: false

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: indigo

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables

plugins:
  - search

copyright: Copyright &copy; 2025 <a href="https://everythingisnoth.ing">Varun Hemachandran</a>

extra:
  generator: false  # Removes "Made with Material for MkDocs" text

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
    - Quick Start: getting-started/quick-start.md
  - User Guide:
    - Overview: user-guide/overview.md
    - Scrapers: user-guide/scrapers.md
    - Database Integration: user-guide/database-integration.md
    - API: user-guide/api.md
    - Tagging System: user-guide/tagging-system.md
  - API Reference:
    - Scrapers: api-reference/scrapers.md
    - Database: api-reference/database.md
    - Utilities: api-reference/utilities.md
  - Developer Guide:
    - Architecture: developer-guide/architecture.md
    - Contributing: developer-guide/contributing.md
    - Code Style: developer-guide/code-style.md
    - Code of Conduct: developer-guide/code-of-conduct.md
  - About:
    - Changelog: about/changelog.md
    - License: about/license.md
